---
version: "3.3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      default:
        ipv4_address: 172.20.1.1
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/plex/config:/config
      - ${DATA}:${DATA}
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      default:
        ipv4_address: 172.20.1.2
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/sonarr/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      default:
        ipv4_address: 172.20.1.3
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/radarr/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      default:
        ipv4_address: 172.20.1.4
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/bazarr/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped
    
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      default:
        ipv4_address: 172.20.1.5
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true
    volumes:
      - ${CONTAINERS}/jackett/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped
    
  nzbhydra2:
    image: linuxserver/nzbhydra2
    container_name: nzbhydra2
    networks:
      default:
        ipv4_address: 172.20.1.6
    ports:
      - 5076:5076
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/nzbhydra2/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped
    
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      default:
        ipv4_address: 172.20.1.7
    ports:
      - 9050:8080
      - 9051:9090
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/sabnzbd/config:/config
      - ${DATA}:${DATA}
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    networks:
      default:
        ipv4_address: 172.20.1.8
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/nzbget/config:/config
      - ${DATA}:${DATA}
    ports:
      - 6789:6789
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    networks:
      default:
        ipv4_address: 172.20.1.9
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped  

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    networks:
      default:
        ipv4_address: 172.20.1.10
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      default:
        ipv4_address: 172.20.1.11
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/lidarr/config:/config
      - ${DATA}:${DATA}
    ports:
      - 8686:8686
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    networks:
      default:
        ipv4_address: 172.20.1.12
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/transmission/config:/config
      - ${DATA}:${DATA}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      default:
        ipv4_address: 172.20.1.14
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  organizr:
    image:  organizr/organizr
    container_name: organizr
    networks:
      default:
        ipv4_address: 172.20.1.15
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
 #     - branch="v2-master"
    volumes:
      - ${CONTAINERS}/organizr/config:/config
    ports:
      - 5056:80
    restart: unless-stopped

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
